### ISSUE TITLE
[Feature] consider whether the `jstrdecode(1)` here should validate JSON first (as it does in the jparse repo)

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#1039]
### Is there an existing issue for this?

- [X] I have searched for existing issues and did not find anything like this

### Describe the feature

Due to something that had to be done for jparse, the current version of jstrdecode in the jparse repo validates JSON before trying to decode it. The question is whether or not that should be here. See also additional comments on this as having this can bring up some other things to consider. If those are deemed a problem there is a simple fix.

### Relevant images, screenshots or other files

Nothing to see.

### Relevant links

Nothing to click.

### Anything else?

One problem is that in the website scripts, if one uses the validate JSON first mode, it breaks the scripts as the quotes are removed. Adding the option to the scripts to disable JSON validation results in a weird output (`- 15`) added to text. I cannot explain this one.

Another problem is that in the tool itself it can be annoying to always have to double quote the input. I don't remember the reason for adding the validation of JSON first but it was due to some issue that was opened.

A possible solution would be to revert the meaning of `-j`: instead of it disabling validation of JSOn it would enable validation of JSON. This would make the tool easier to use and in the case that it needs to validate JSON it is still possible. Since it's unlikely anyone is using it (yet?) it should not be a big problem.

**Comment by xexyl** [comment]
Feel free to assign me. I'm happy to flip the meaning of `-j` in `jstrdecode` and then sync to this repo. I think actually, in retrospect, it might be better to do that, but since you thought an issue should be open to discuss this I'm not going to do that yeet.

Must go afk a bit but when back I'll look at any issues I have not done yet and that do not need any clarifications.

**Comment by xexyl** [comment]
Background and post IOCCC28.  Okay. So for now we'll keep in the current version. 

The question however is should the meaning of `-j` be reverted? If so I can do that ahead of time and then when it's time to sync here we can just sync and commit.

**Comment by lcn2** [comment]
Thank you for opening this, @xexyl 

For now, this remains a low priority post-IOCCC28 issue. 

We need to discuss why it should happen in the 2.1 release of this repo, and come to a conclusion on that before issue #1038 closes.

But all that is not as high priority as getting the **Great Form Merge** done in the other repo.

**Comment by xexyl** [comment]
> Thank you for opening this, @xexyl
> 
> For now, this remains a low priority post-IOCCC28 issue.
> 
> We need to discuss why it should happen in the 2.1 release of this repo, and come to a conclusion on that before issue #1038 closes.
> 
> But all that is not as high priority as getting the **Great Form Merge** done in the other repo.

Whatever you think might be best. In retrospect I think that, since I cannot remember why we needed to validate JSON, and since one can always use the option if they need, it might be better if the tool has `-j` enable JSON validation. Also since `jstrencode(1)` does not require double quotes and since it's the inverse of jstrdecode ... it might be better to not have it by default.

But yes we can discuss it later on.

As for the great fork merge. I fixed another link in the FAQ and shortened the thanks file a bit (very little bit) but for now I'm holding off on committing it. I'm going to be doing other things I think. I got three important issues fixed today so that's good progress. Hopefully tonight will be better and I can be more alert tomorrow.

**Comment by lcn2** [comment]
> Whatever you think might be best. In retrospect I think that, since I cannot remember why we needed to validate JSON, and since one can always use the option if they need, it might be better if the tool has -j enable JSON validation. Also since jstrencode(1) does not require double quotes and since it's the inverse of jstrdecode ... it might be better to not have it by default.

You raise a very good question above, @xexyl 

We can, perhaps, see a theoretical reason why we needed to validate the JSON, but as you point out it might be better to not to have it on by default. 

If it is not on my default, then what happens to this issue? How might it be resolved under that condition?

**Comment by xexyl** [comment]
> > Whatever you think might be best. In retrospect I think that, since I cannot remember why we needed to validate JSON, and since one can always use the option if they need, it might be better if the tool has -j enable JSON validation. Also since jstrencode(1) does not require double quotes and since it's the inverse of jstrdecode ... it might be better to not have it by default.
> 
> You raise a very good question above, @xexyl
> 
> We can, perhaps, see a theoretical reason why we needed to validate the JSON, but as you point out it might be better to not to have it on by default.
> 
> If it is not on my default, then what happens to this issue? How might it be resolved under that condition?

I honestly don't remember what it was meant to solve. But just as one can use `-j` to disable it so could they use it to enable the validation.

If it's on by default then some issues arise depending on the args passed to the program. For instance in the website scripts the quotes are removed so it fails to validate. I tried to add `-j` to the scripts (thinking that option existed in mkiocccentry due to the unfortunate environment issue resolved earlier) but that added the strange `- 15` or whatever the number was .. it was close to that anyway. I could not explain that one. It made no sense at all to me.

An annoying fact of having it enabled by default is when typing one has to always type double quotes which means they also have to use single quotes. So perhaps in the case validation is needed one can use the `-j`? (Unless of course it is discovered that it has to be enabled by default.)

**Comment by lcn2** [comment]
So would disabling the JSON check by default mean that in the "other repo", the bin scrips would not have to change?

**Comment by xexyl** [comment]
> So would disabling the JSON check by default mean that in the "other repo", the bin scrips would not have to change?

Precisely. Just like it is now (with the mkiocccentry repo).

**Comment by xexyl** [comment]
Checking make release over there now .. assuming all is good I'll commit and then the jparse can be synced. I however won't do that part today I think but I can do it in the morning.

**Comment by xexyl** [comment]
New version released. Now `jstrdecode -j` enables JSON parsing.

**Comment by xexyl** [comment]
I found something fun though. Consider this.

`-j` enables parsing. Okay and `-d` means you don't have to give a surrounding `"`. But then what happens if you do...

```sh
$ jstrdecode -j -d '"foo"'
Warning: json_decode: found non-\-escaped char: 0x22
Warning: main: error while decoding processing arg: 0
```

So `-j` and `-d` conflict. Perhaps this should be noted in documentation and maybe the usage string? What do you think?

**Comment by xexyl** [comment]
Actually using double quotes with `-d` without `-j` also triggers it (that makes sense). It seems like you can't use `-d` and specify quotes at all; and since `-j` needs those quotes it cannot be used together.

I can update the usage and man page but I think maybe not now. I'll also have to update the documentation.

**Comment by xexyl** [comment]
I fixed it now. The use together of both options is now an error. That's all I'm doing today .. tomorrow can test make www.

**Comment by lcn2** [comment]
> I fixed it now. The use together of both options is now an error. That's all I'm doing today .. tomorrow can test make www.

I think this is a good plan to code and document that both options together is now an error.

If the fixes this straightforward, is there any reason why we shouldn't include this in version 2.1 of this repo release?

**Comment by xexyl** [comment]
> > I fixed it now. The use together of both options is now an error. That's all I'm doing today .. tomorrow can test make www.
> 
> I think this is a good plan to code and document that both options together is now an error.
> 

Yes that's now done.

> If the fix this straightforward, is there any reason why we shouldn't include this in version 2.1 of this repo release?

I can't think of any real reason. I can however think of reasons that we might want it in.

Here was a useful bug fix.

    Bug fix JSON debug output for numbers
    
    Due to a flow control problem, the floating notation flag was always set
    to true if no errors were found and a '.' was found in the string. This
    meant that the F flag was always present even for non-floating point
    numbers.


And some improvements:

- `vjson_fprint()` was modularised.

For two examples. Documentation was also improved quite a bit.

**Comment by lcn2** [comment]
We believe we have addressed all of the current questions that still need answering at this time. If we've missed something or something else needs to be clarified, please ask again.

**Comment by lcn2** [comment]
In light of [GH-issuecomment-2563085398](https://github.com/ioccc-src/mkiocccentry/issues/1039#issuecomment-2563085398), we have added this issue to the TODO list of #1038 : unless you think that would be unwise @xexyl 

Please remember that completing tasks (which exclude all issues in this repo) need to resume the **Great Fork Merge** remain the **TOP PRIORITY**.

It is our goal to finish the **Great Fork Merge** by or on Saturday 2024 Dec 28.

**Comment by xexyl** [comment]
This is looking good. The problem locations started immediately upon generating index.html files for entries and it's in the middle now .. still not awake enough to work on the other things though I'm afraid. I imagine I'll be able to a while later.

**Comment by xexyl** [comment]
As for the merge by tomorrow. I hope I can get that stuff in. Thanks for the warning! I'll do my best.

**Comment by xexyl** [comment]
Shouldn't this be closed as resolved? Or do you have a reason to keep it open? I'm leaving in just a moment. Tomorrow - after the fork merge - I can update the links in this repo to the main website one. At the same time I can include the submit server links.

**Comment by lcn2** [comment]
Thank you @xexyl for exploring the many options, helping select a solution, and doing the work to resolve this important issue!

**Comment by xexyl** [comment]
> Thank you @xexyl for exploring the many options, helping select a solution, and doing the work to resolve this important issue!

You are most welcome! I'm glad it's sorted now.
