### ISSUE TITLE
Enhancement: fix json man pages

### ISSUE THREAD

**Issue by xexyl** [ioccc-src/mkiocccentry#455]
There are two parts to this issue.

One is easy enough. Am I incorrect in saying that the man pages

- jnum_chk.8
- jnum_gen.8
- jsemcgen.8
- jsemtblgen.8
- jstr_test.8

should actually be in the jparse/man/man8 directory ? I'm not sure why they're not already actually. If they should be I can move them over in a commit in the next day or so.

The other part is that as far as the semantics tables go in the man pages:

- jsemcgen.8
- jsemtblgen.8 
- all_sem_ref.8 (does this belong in jparse/man/man8 ?)

... the description is incorrect. I've not tried to figure out the semantics tables but it would be helpful since you created the scripts and tool to update the description of these man pages.

**Comment by lcn2** [comment]
Fixed with commit f5376bc3fad9980417b8f753a8087c38b0bb9344

**Comment by xexyl** [comment]
> Fixed with commit [f5376bc](https://github.com/ioccc-src/mkiocccentry/commit/f5376bc3fad9980417b8f753a8087c38b0bb9344)

Thank you! I'll take a look and maybe it'll help me out for later on - like the jparse repo when that time comes.

**Comment by xexyl** [comment]
Hmm ... I'm not sure what changed? I still see:

```
       This tool creates JSON semantics tables. In the case of the IOCCC, we use the jsemcgen(8) script as a wrapper to making these tables, which are
       are an important part of the chkentry(1) tool.  As the chkentry(1) tool is a vitally important part of the IOCCC judging process these tools are
       also vital in running the IOCCC but at a lower level.  If the -s option is used the json_arg is a string.  Otherwise it is assumed to be a file.

```

which is what I wrote before and which still refers to the IOCCC. What changed then?

**Comment by xexyl** [comment]
As for the move to soup/man I'm not sure if this is good because most people won't think to look under soup for man pages, right?

But I see that you maybe resolved the make install issue at least. Or .. perhaps not:

```sh
install -v -d -m 0775 /usr/local/share/man/man3
install -v -m 0444 man/man3/dbg.3  man/man3/err.3 man/man3/msg.3 man/man3/warn.3 man/man3/werr.3 man/man3/printf_usage.3 man/man3/warn_or_err.3  /usr/local/share/man/man3
install: man/man3/dbg.3 -> /usr/local/share/man/man3/dbg.3
install: man/man3/err.3 -> /usr/local/share/man/man3/err.3
install: man/man3/msg.3 -> /usr/local/share/man/man3/msg.3
install: man/man3/warn.3 -> /usr/local/share/man/man3/warn.3
install: man/man3/werr.3 -> /usr/local/share/man/man3/werr.3
install: man/man3/printf_usage.3 -> /usr/local/share/man/man3/printf_usage.3
install: man/man3/warn_or_err.3 -> /usr/local/share/man/man3/warn_or_err.3

dbg: make install starting

install -v -d -m 0775 /usr/local/lib
install -v -m 0444 dbg.a /usr/local/lib
install: dbg.a -> /usr/local/lib/dbg.a
install -v -d -m 0775 /usr/local/include
install -v -m 0444 dbg.h /usr/local/include
install: dbg.h -> /usr/local/include/dbg.h
install -v -d -m 0775 /usr/local/bin
install -v -m 0555  dbg_test dbg_example /usr/local/bin
install: dbg_test -> /usr/local/bin/dbg_test
install: dbg_example -> /usr/local/bin/dbg_example
```

Doesn't list the other man pages under dbg ?

Also I now remember that I need to make man pages for the separate dyn_array functions - I just am not sure how to categorise them yet or if they should all just be the same category (as in all link to the main man page). What do you think?

Also there's this problem:


```sh
test_jparse: make install starting

v -d -m 0775 /usr/local/bin
bash: line 1: v: command not found
make[2]: [install] Error 127 (ignored)
v -m 0555  jnum_chk /usr/local/bin
bash: line 1: v: command not found
make[2]: [install] Error 127 (ignored)

test_jparse: make install complete
```

which I guess might be a missing or empty `INSTALL` variable though I've not looked at that Makefile yet.

So I'm not sure this issue is resolved on any part: the fix to the text in the semantics tables and the missing debug man pages and other things?

**Comment by xexyl** [comment]
> Also there's this problem:
> 
> ```shell
> test_jparse: make install starting
> 
> v -d -m 0775 /usr/local/bin
> bash: line 1: v: command not found
> make[2]: [install] Error 127 (ignored)
> v -m 0555  jnum_chk /usr/local/bin
> bash: line 1: v: command not found
> make[2]: [install] Error 127 (ignored)
> 
> test_jparse: make install complete
> ```
> 
> which I guess might be a missing or empty `INSTALL` variable though I've not looked at that Makefile yet.

This was indeed the problem. Fixed in https://github.com/ioccc-src/mkiocccentry/pull/456/commits/50423e90a19844200b794eaeb01f73951c905bd6.

**Comment by xexyl** [comment]
> > Also there's this problem:
> > ```shell
> > test_jparse: make install starting
> > 
> > v -d -m 0775 /usr/local/bin
> > bash: line 1: v: command not found
> > make[2]: [install] Error 127 (ignored)
> > v -m 0555  jnum_chk /usr/local/bin
> > bash: line 1: v: command not found
> > make[2]: [install] Error 127 (ignored)
> > 
> > test_jparse: make install complete
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which I guess might be a missing or empty `INSTALL` variable though I've not looked at that Makefile yet.
> 
> This was indeed the problem. Fixed in [50423e9](https://github.com/ioccc-src/mkiocccentry/commit/50423e90a19844200b794eaeb01f73951c905bd6).
> 
> However I see now that you updated that Makefile. To prevent any problems (since I might need to make changes that could conflict) I will close that commit and then redo it starting from the commit you just made.
> 
See updated comment https://github.com/ioccc-src/mkiocccentry/issues/455#issuecomment-1368926132 for the commit with the fix. Also in that pull request added `tags` to some `.PHONY` rules that did not have it.

**Comment by xexyl** [comment]
This is the issue that I know is not resolved.

Specifically this part of the issue is not resolved:

> The other part is that as far as the semantics tables go in the man pages:
> 
> * jsemcgen.8
> * jsemtblgen.8
> * all_sem_ref.8 (does this belong in jparse/man/man8 ?)
> 
> ... the description is incorrect. I've not tried to figure out the semantics tables but it would be helpful since you created the scripts and tool to update the description of these man pages.

**Comment by lcn2** [comment]
> This is the issue that I know is not resolved.
> 
> Specifically this part of the issue is not resolved:
> 
> > The other part is that as far as the semantics tables go in the man pages:
> > 
> > * jsemcgen.8
> > * jsemtblgen.8
> > * all_sem_ref.8 (does this belong in jparse/man/man8 ?)
> > 
> > ... the description is incorrect. I've not tried to figure out the semantics tables but it would be helpful since you created the scripts and tool to update the description of these man pages.

See the new issue #475

**Comment by xexyl** [comment]
> > This is the issue that I know is not resolved.
> > Specifically this part of the issue is not resolved:
> > > The other part is that as far as the semantics tables go in the man pages:
> > > 
> > > * jsemcgen.8
> > > * jsemtblgen.8
> > > * all_sem_ref.8 (does this belong in jparse/man/man8 ?)
> > > 
> > > ... the description is incorrect. I've not tried to figure out the semantics tables but it would be helpful since you created the scripts and tool to update the description of these man pages.
> 
> See the new issue #475

Thank you. Replied.
